[tool.poetry]
name = "MY_PROJECT"
version = "0.1.0"
description = ""
authors = ["ddiepgrond <ddiepgrond@deloitte.nl>"]
license = "Confidential"
readme = "README.md"
classifiers = ["Private :: Do not Upload"]
exclude = ["**"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.3"
numpy = "^1.25.1"
ipykernel = "^6.25.0"
openpyxl = "^3.1.2"
matplotlib = "^3.7.2"
strenum = "^0.4.15"
pytz = "^2023.3"
azure-identity = "^1.14.0"
azure-storage-file-datalake = "^12.13.1"
xlrd = "^2.0.1"
seaborn = "^0.13.0"
pyodbc = "^5.0.1"
sqlalchemy = "^2.0.25"
python-dotenv = "^1.0.1"


[tool.poetry.group.dev.dependencies]
black = {version = "^23.7.0", allow-prereleases = true}
flake8 = "^6.1.0"
pre-commit = "^3.4.0"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
py310 = true

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "MY_PROJECT",
]
